config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :stores do
    resources :products, only: [:index, :show, :new, :create]
  end

  resources :stores, only: [:index, :show, :new, :create]

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :store
	validates :title, presence: true
	validates :description, length: {minimum: 10}
	validates :price, numericality: {greater_than: 0}
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :products
	validates :location, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

before_filter :load_store

def show
	@product = Product.find(params[:id])
end

def index
	@products = @store.products.all
end

def new 
	@product = @store.products.new
end

def create
	@product = @store.products.new(product_params)

	respond_to do |format|
		if @product.save
       		format.html { redirect_to store_products_path, notice: 'Product was successfully created.' }
       		format.json { render :show, status: :created, location: @product }
		else
      	 	format.html { render :new }
       		format.json { render json: @product.errors, status: :unprocessable_entity }
		end
	end
end

private 
def load_store
	@store = Store.find(params[:store_id])
end

 private
 def product_params
 	params.require(:product).permit(:title, :description, :price)
 end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end
	

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

def index
	@stores = Store.all
end

def show
	@store = Store.find(params[:id])
end

def new
	@store = Store.new
end

 def create
   @store = Store.new(store_params)

   respond_to do |format|
     if @store.save
       format.html { redirect_to "/stores", notice: 'Store was successfully created.' }
       format.json { render :show, status: :created, location: @store }
     else
       format.html { render :new }
       format.json { render json: @store.errors, status: :unprocessable_entity }
     end
   end
 end

 private
 def store_params
 	params.require(:store).permit(:location)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EcommerceApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div><%= link_to "Home" , "/" %></div>
<div><%= link_to "Stores Index" , "/stores" %></div>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for([@store, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
  

app/views/products/index.html.erb
<h2><%= "Here are all the products for #{@store.location}" %></h2>

<ul>
<% @products.each do |product| %>
	<li><%= link_to "#{product.title}" , "/stores/#{product.store_id}/products/#{product.id}" %></li></br>
<% end %>
</ul>
<p><%= link_to "Create a new product" , new_store_product_path %></p>

app/views/products/new.html.erb
<h2><%="Create a new product for #{@store.location}:" %></h2>

<%= render 'form' %>

<%=link_to "Back" , "/stores/#{@store.id}/products" %>

app/views/products/show.html.erb
<!--- list the product details -->
<h2><%="Check out this awesome product from our #{@store.location} store!" %></h2>

<p><%= "----" %></p>
<p><%= "Title: #{@product.title}" %></p>
<p><%= "Description: #{@product.description}" %></p>
<p><%= "Price: $" + ('%.2f' % @product.price.to_s) %></p>
<p><%= "----" %></p>

<p><%= link_to "All products available in #{@store.location}" , "/stores/#{@product.store_id}/products" %></p>

app/views/static_pages/home.html.erb
<h1>Welcome to Clare's generic e-commerce website!</h1>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  
<% end %>

app/views/stores/index.html.erb
<h2>Here are all our wonderful stores: </h2>

<% @stores.each do |s| %>
	<p><%= "Store No. #{s.id} > " %><%= link_to "#{s.location}" , "/stores/#{s.id}/products" %></p>
<% end %>

<!-- create a new store entry section goes here -->
<p><%= link_to "Create a new store" , new_store_path %></p>

app/views/stores/new.html.erb
<h2>To create a new store, simply enter the store location:</h2>

<%= render 'form' %>

<%=link_to "Back" , "/stores" %>